Feat: add use quickjs bytecode
openkraken/website pull request #181
Opened 2021-10-19 11:30 UTC by andycall

2021-10-19 11:43 UTC, cnryb commented on docs/guide/advanced/use-quickjs-bytecode.md
> +通过[实验证明](https://github.com/openkraken/kraken/pull/446), 采用 Quickjs Bytecode 进行加载能够将 JS 加载时间减少 58.12%。
这个实验中好像没有用到 bytecode

2021-10-20 02:58 UTC, answershuto commented
等分支合并以后再合并文档。

2021-11-02 02:29 UTC, wssgcg1213 commented on .umirc.ts
> +            title: '使用 Quickjs Bytecode 提升加载性能',
Quickjs -> QuickJS

2021-11-02 02:31 UTC, wssgcg1213 requested changes

2021-11-02 02:31 UTC, wssgcg1213 commented on .umirc.ts
>              title: '使用 Fluter Widget 自定义元素',
Fluter -> Flutter

2021-11-02 02:31 UTC, wssgcg1213 commented on docs/guide/advanced/use-quickjs-bytecode.md
> +由于不同版本之间的 quickjs bytecode 并不一定可以完全兼容，因为 kraken 将所生成的 bytecode 文件命名为 `.kbc1` 格式。
`QuickJS` 
`Kraken`

2021-11-03 11:53 UTC, wssgcg1213 approved these changes

2021-11-04 02:27 UTC, answershuto approved these changes

2021-11-04 02:28 UTC, answershuto commented
冲突了

2021-11-04 06:19 UTC, merged