feat: add custom element doc
openkraken/website pull request #184
Opened 2021-11-02 14:03 UTC by andycall

2021-11-03 11:55 UTC, wssgcg1213 commented on .umirc.ts
> +            title: '开发 Rendering 插件',
我们是不是新造了概念?

2021-11-03 11:56 UTC, wssgcg1213 commented on docs/plugins/plugin/rendering-development.md
> +# 开发一个渲染插件
用 `扩展自定义 Element` 这个概念更简单一点?

2021-11-03 11:58 UTC, wssgcg1213 requested changes
这两篇文章对应的是两种插件类型, 我觉得插件是一种类型就可以, 用如何扩展 `API` 和 扩展 `Element` 的表述来更简单, 因为理论上这些扩展能力之间并不是互斥的

2021-11-04 02:27 UTC, answershuto commented on .umirc.ts
> +            title: '开发 Rendering 插件',
+1 ,概念可以简单易懂一些

2021-11-04 02:53 UTC, wssgcg1213 commented
https://openkraken.com/plugins/plugin/introduction  参考已有的这篇里面的介绍就行了, 两部分

```
Kraken 在设计上给插件提供了两种能力的扩展：

渲染能力扩展
API 能力扩展
```

2021-12-20 16:56 UTC, andycall commented
后续扩展采用 widget 的方式，以后 Element 的扩展方式不再支持。

https://github.com/openkraken/kraken/pull/904/files

2021-12-20 16:56 UTC, closed without merging