feat: add architecture overview
openkraken/website pull request #207
Opened 2022-04-06 08:27 UTC by andycall

2022-04-07 03:12 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +(HTML+CSS+JS) + Rendering = Pixel.
这个公式有点怪怪的

```
Kraken(HTML, CSS, JS) = UI
```

2022-04-07 03:12 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +Kraken 是一款采用基于 Flutter 而实现的自绘渲染引擎。它使用 W3C 标准的 HTML，CSS，JavaScript，通过一系列的计算，生成 GUI 画面，并支持通过 JavaScript 实现对画面的实时交互。
GUI 画面 -> 用户界面 

 (User Interface)

2022-04-07 03:13 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +(HTML+CSS+JS) + Rendering = Pixel.
多元函数的变形  `f(x) = y`

2022-04-07 03:54 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +
建议这个不要讲比较好, 可以留到 Bridge

2022-04-07 11:53 UTC, wssgcg1213 requested changes
文章的主线应该还是以架构分层分开来讲，现在写的是渲染流程渲染管线, 这个放到 webkit 的介绍文章里也一样成立。

总分结构, 文章开头先放一张架构分层图, 再分层介绍每一层的职责，依赖关系

2022-04-07 11:53 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +对于上诉的数据，渲染引擎开始的第一步是处理 HTML。熟悉 HTML 的同学都知道，HTML 是由多个不同的标签组成，标签与标签可以嵌套，可以同级，他们之间组成了树形的结构。
typo: `上诉`

2022-04-07 11:53 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +
这里应当介绍 Kraken 与浏览器差异是同时可以接受 kbc1/js/html 三种类型作为入口, 它们都可以生成 DOM 结构, 区别是前者是在 JS 引擎里执行调用 DOM API 生成, 后者是 HTMLParser 生成

2022-04-07 11:53 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +## 基于 DOM Tree 的 CSS
DOM Tree -> DOM 树

2022-04-07 11:53 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +<img src="https://kraken.oss-cn-hangzhou.aliyuncs.com/images/20220406122844.jpg" width="600"  />
这张图我重新画一张吧, 体现分层架构

2022-04-07 11:55 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +最终 Kraken 和 Flutter 相互融合的架构如下：
和 Flutter 融合不是我们的目标，如上文所述 Flutter 是实现 Kraken 的一种技术路线，基于这个点我们可以做到与 Flutter Widgets 的共存

2022-04-07 11:57 UTC, answershuto commented
后续要规划的文章的点最好都在里面透出。

2022-04-13 09:32 UTC, wssgcg1213 approved these changes

2022-04-13 09:34 UTC, wssgcg1213 commented on docs/blog/architecture-overview.md
> +**C++ 与 Dart 之间的通信**
这里用 `相互调用` 会好一点?

2022-04-13 11:31 UTC, answershuto approved these changes

2022-04-13 12:31 UTC, merged